site_name: FogLedger-Iota

theme:
  name: material
  palette:  
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: auto)'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
  language: en

repo_name: larsid/FogLedger-Iota
repo_url: https://github.com/larsid/FogLedger-Iota/
edit_uri: ""

extra:
  version:
    provider: mike

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/WesleiSantos
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/weslei-santos-8858bb173/

copyright: |
  &copy; 2023 <a href="https://github.com/larsid/FogLedger-Iota/"  target="_blank" rel="noopener">LARSID</a>

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: 'index.md'
  - Getting started: 'quickstart.md'

  - DLTs:
    - IOTA Tangle: 'iota/README.md'
